apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
    - namespace.yaml
    - service.yaml
    - deployment.yaml
    - persistentVolume.yml
    - persistentVolumeClaim.yml
    - mongodb.yaml

generatorOptions:
 disableNameSuffixHash: true
