apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: airflow
    version: v1


images:
- name: apache/airflow
  newTag: 2.3.0
