apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mywebapp
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: mywebapp
    version: v1


images:
- name: my.image.registry/nginx
  newTag: 1.4.0
