apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-search-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: search-app
    server: {{ .Values.spec.destination.server }}
  project: search-app
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: search-app/microservices/backend/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
