apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-new-Application-be
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: new-Application-be
    server: {{ .Values.spec.destination.server }}
  project: new-Application-project
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: new-application/microservices/backend/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
