apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-redis
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: argocd-redis
    version: v1
- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: argocd-redis
    version: v1

images:
- name: redis
  newTag: 7.2.7-alpine
