apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: nginx
    version: v1
- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: nginx
    version: v1

images:
- name: docker.io/nginx
  newTag: alpine
