apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: application-example-be
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: application-example-be
    version: v1


images:
- name: gcr.io/google-samples/microservices-demo/shippingservice
  newTag: v0.4.1
