apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example-2
  labels:
    app: app-example-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-example-2
  template:  
    metadata:
      labels:
        app: app-example-2
    spec:
      containers:
      - name: app-example-2
        image:  < REGISTRY / IMAGE >
        ports:
          - containerPort: 80
        imagePullPolicy: Always

