apiVersion: v1
kind: Service
metadata:  
  name: app-example-2
  annotations:
    app.access.url:  < URL >
spec: 
  type: ClusterIP
  ports: 
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app-example-2


    
