apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: search-app
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: search-app
    version: v1
- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: search-app
    version: v1

images:
- name: docker.elastic.co/elasticsearch/elasticsearch
  newTag: 7.12.0
