apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: grafana
    version: v1

images:
- name: grafana/grafana
  newTag: 5.4.3
