apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
    - notifications-cm.yaml
    - notifications-controller-deployment.yaml
    - notifications-controller-metrics-service.yaml
    - notifications-controller-network-policy.yaml
    - notifications-controller-role.yaml
    - notifications-controller-rolebinding.yaml
    - notifications-controller-sa.yaml
    - notifications-secret.yaml

generatorOptions:
 disableNameSuffixHash: true
