apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
    - applicationset-controller-service.yaml
    - applicationset-controller-sa.yaml
    - applicationset-controller-rolebinding.yaml
    - applicationset-controller-role.yaml
    - applicationset-controller-network-policy.yaml
    - applicationset-controller-deployment.yaml

generatorOptions:
 disableNameSuffixHash: true
