- op: replace
  path: /spec/template/spec/containers/0/image
  value: docker.elastic.co/elasticsearch/elasticsearch

- op: add
  path: /spec/template/spec/containers/0/envFrom
  value:
    - configMapRef:
        name: env-configs

- op: add
  path: /spec/revisionHistoryLimit
  value: 2
