apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-grocery
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: grocery
    server: {{ .Values.spec.destination.server }}
  project: grocery
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: grocery-project/microservices/backend/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
