apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fullstack-be
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: backend
    version: v1
- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: backend
    version: v1
- path: ./patches/postgreql-deployment-patch.yaml
  target:
    kind: Deployment
    name: postgres
    version: v1

images:
- name: docker.io/python
  newTag: 3.11-slim
