apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hello
    server: {{ .Values.spec.destination.server }}
  project: hello
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: hello-world/microservices/backend/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
