apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-service
  labels:
    app: currency-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-service
  template:  
    metadata:
      labels:
        app: currency-service
    spec:
      containers:
      - name: currency-service
        image:  < REGISTRY / IMAGE >
        ports:
          - containerPort: 7000
        imagePullPolicy: Always

