apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:  
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image:  < REGISTRY / IMAGE >
        command: ["flask", "run", "--host=0.0.0.0"]
        ports:
          - containerPort: 80
        imagePullPolicy: Always

