apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app-example-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app-example-2
    server: {{ .Values.spec.destination.server }}
  project: app-example-2
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: app-example-2/microservices/backend/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
