apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 

namespace: argocd-notification

configMapGenerator:
  - envs:
      - config.env 
    name: env-configs
    namespace: argocd-notification



generatorOptions:
 disableNameSuffixHash: true
