apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: cert-manager
    version: v1

# images:
# - name: grafana/grafana
#   newTag: 5.4.3
