apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-mapping
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: app-1
    version: v1
- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: app-1
    version: v1

# images:
# - name: docker.io/nginx
#   newTag: alpine
