apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-currency-service-be
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: currency-service-be
    server: {{ .Values.spec.destination.server }}
  project: currency-service
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: currency-service/microservices/backend/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
