apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
    - dex-server-deployment.yaml
    - dex-server-network-policy.yaml
    - dex-server-role.yaml
    - dex-server-rolebinding.yaml
    - dex-server-sa.yaml
    - dex-server-service.yaml
    - argocd-secret.yaml
    - cmd-params-cm.yaml
    - gpg-keys-cm.yaml
    - rbac-cm.yaml
    - ssh-known-hosts-cm.yaml
    - tls-certs-cm.yaml

generatorOptions:
 disableNameSuffixHash: true
