apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
    - namespace.yaml
    - dex-server-deployment.yaml
    - dex-server-network-policy.yaml
    - dex-server-role.yaml
    - dex-server-rolebinding.yaml
    - dex-server-sa.yaml
    - dex-server-service.yaml

generatorOptions:
 disableNameSuffixHash: true
