apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adservice
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: adservice
    version: v1
- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: adservice
    version: v1

images:
- name: gcr.io/google-samples/microservices-demo/adservice
  newTag: v0.4.1
