apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fullstack-fe
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: frontend
    version: v1
- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: frontend
    version: v1

images:
- name: docker.io/node
  newTag: 18-alpine
