apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello-gitops
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: hello-gitops
    version: v1


images:
- name: mansong/hello-gitops
  newTag: "34"
