apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
    - namespace.yaml
    - applicaion-controller-deployment.yaml
    - application-controller-service.yaml
    - application-controller-statefulset.yaml
    - application-controller-sa.yaml
    - application-controller-role.yaml
    - application-controller-rolebinding.yaml
    - application-controller-cm.yaml

generatorOptions:
 disableNameSuffixHash: true
