apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-fullstack-project-frontend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: fullstack-fe
    server: {{ .Values.spec.destination.server }}
  project: fullstack-project
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: fullstack-project/microservices/frontend/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
