apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-be
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ecommerce-be
    server: {{ .Values.spec.destination.server }}
  project: ecommerce
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: ecommerce/microservices/backend/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
    kustomize:
      buildOptions: "--enable-helm"