apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
    - namespace.yaml
    - repo-server-service.yaml
    - repo-server-sa.yaml
    - repo-server-network-policy.yaml
    - repo-server-deployment.yaml


generatorOptions:
 disableNameSuffixHash: true
