apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-example-2
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: app-example-2
    version: v1


images:
- name: docker.io/nginx
  newTag: alpine
