apiVersion: apps/v1
kind: Deployment
metadata:
  name: wzleagues-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wzleagues-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: wzleagues-app
    spec:
      containers:
      - name: wzleagues-app
        image: gcr.io/wzleagues/wzleagues:f9ba370337849c7f0af8d57d6d11b913d820d0df
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m