apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mynamespace
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-app
      role: database
  template:
    metadata:
      labels:
        app: mern-app
        role: database
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"