apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
    - namespace.yaml
    - service.yaml
    - deployment.yaml
    - db_deploy.yaml
    - db_service.yaml

generatorOptions:
 disableNameSuffixHash: true
