apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-mapping
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev-mapping
    server: {{ .Values.spec.destination.server }}
  project: dev-mapping
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: project-deployment/microservices/backend/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
