apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:  
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image:  < REGISTRY / IMAGE >
        ports:
          - containerPort: 50051
        imagePullPolicy: Always

