apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-application-example
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: application-example-be
    server: {{ .Values.spec.destination.server }}
  project: application-example
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: application-example/microservices/backend/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
