apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-wzleagues-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: wzleagues-app
    server: {{ .Values.spec.destination.server }}
  project: wzleagues-app
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: leagues/microservices/backend/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
