apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nginx
    server: {{ .Values.spec.destination.server }}
  project: nginx
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: nginx/microservices/backend/kustomize/overlays/staging
    targetRevision: {{ .Values.spec.source.targetRevision }}
