apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-example-be
  labels:
    app: application-example-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-example-be
  template:  
    metadata:
      labels:
        app: application-example-be
    spec:
      containers:
      - name: application-example-be
        image:  < REGISTRY / IMAGE >
        ports:
          - containerPort: 50051
        imagePullPolicy: Always

