apiVersion: v1
kind: Service
metadata:  
  name: application-example-be
  annotations:
    app.access.url:  < URL >
spec: 
  type: ClusterIP
  ports: 
  - name: http
    port: 80
    protocol: TCP
    targetPort: 50051
  selector:
    app: application-example-be


    
