apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guestbook
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: guestbook
    version: v1
