apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:  
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: adservice
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
          privileged: false
          readOnlyRootFilesystem: true
        image:  < REGISTRY / IMAGE >
        ports:
          - containerPort: 9555
        imagePullPolicy: Always