apiVersion: v1
kind: Service
metadata:  
  name: adservice
  annotations:
    app.access.url:  < URL >
spec: 
  type: ClusterIP
  ports: 
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9555
  selector:
    app: adservice


    
