apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: search-app
  labels:
    app: search-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-app
  template:
    metadata:
      labels:
        app: search-app
    spec:
      containers:
        - name: search-app
          image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
          ports:
            - containerPort: 9200
          imagePullPolicy: IfNotPresent