apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello-world
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: hello
    version: v1
- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: hello
    version: v1

# images:
# - name: docker.io/monopole
#   newTag: hello:1
