apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mynamespace
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: api
    version: v1


images:
- name: ismail55/backend
  newTag: 1.0.0
