apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 


configMapGenerator:
  - envs:
      - config.env 
    name: mongodb-config
    namespace: mynamespace

secretGenerator:
  - name: mongo-secrets
    envs:
      - secret.env
    namespace: mynamespace


generatorOptions:
 disableNameSuffixHash: true
