apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paymentservice-fe
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: frontend
    version: v1

images:
- name: gcr.io/google-samples/microservices-demo/frontend
  newTag: v0.4.1
