apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
    - namespace.yaml
    - redis-deployment.yaml
    - redis-network-policy.yaml
    - redis-role.yaml
    - redis-rolebinding.yaml
    - redis-sa.yaml
    - redis-service.yaml

generatorOptions:
 disableNameSuffixHash: true
