apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-1
  name: app-1-service
  namespace: default
spec:
  type: NodePort
  ports:
  - name: webport
    port: 8000
    targetPort: 8000
  selector:
    app: app-1