apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: argocd-dex-server
    version: v1
- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: argocd-dex-server
    version: v1

images:
- name: ghcr.io/dexidp/dex
  newTag: v2.41.1
