apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization


configMapGenerator:
  - envs:
      - config.env 
    name: env-configs
    namespace: grocery-be-deployment



generatorOptions:
 disableNameSuffixHash: true
