apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mynamespace-fe
  
resources:
- ../../base

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: frontend
    version: v1


images:
- name: ismail55/frontend
  newTag: 1.0.0
