apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 


configMapGenerator:
  - envs:
      - config.env 
    name: env-configs
    namespace: fullstack-be

secretGenerator:
 - name: backend-secret
   envs:
     - backend-secret.env
   namespace: fullstack-be

 - name: postgreql-secret
   envs:
     - secret.env
   namespace: fullstack-be


generatorOptions:
 disableNameSuffixHash: true
