apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paymentservice-be
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: paymentservice
    version: v1


images:
- name: gcr.io/google-samples/microservices-demo/paymentservice
  newTag: v0.4.1
