apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-advertisment
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: adservice
    server: {{ .Values.spec.destination.server }}
  project: advertisment
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: advertisemenet/microservices/ad-service/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
