apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: guestbook
    server: {{ .Values.spec.destination.server }}
  project: guestbook
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: guestbook/microservices/backend/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
