apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-mern-application
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mynamespace
    server: {{ .Values.spec.destination.server }}
  project: mern-application
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: mern-application/microservices/backend/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
