apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: result
  
resources:
- ../../base
- envs

patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: result
    version: v1


# images:
# - name: docker.io/result
#   newTag: alpine
