apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
    - server-service.yaml
    - server-sa.yaml
    - server-rolebinding.yaml
    - server-role.yaml
    - server-network-policy.yaml
    - server-metrics.yaml
    - server-deployment.yaml



generatorOptions:
 disableNameSuffixHash: true
