apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-bookstore-fe
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: frontend-service
    server: {{ .Values.spec.destination.server }}
  project: bookstore
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: book-store/microservices/backend/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
