apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-airflow-backend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: airflow
    server: {{ .Values.spec.destination.server }}
  project: airflow
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: airflow/microservices/backend/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
